package exception;

public class UsuarioInseridoComSucessoException extends Exception{
    public UsuarioInseridoComSucessoException(){
        super("Usu√°rio inserido com sucesso!");
    }
}
